import js from '@eslint/js'
import prettier from 'eslint-config-prettier/flat'
import vue from 'eslint-plugin-vue'
import globals from 'globals'
import tseslint from 'typescript-eslint'

/**
 * Why `src/output/` may not reach into `src/main/`. Stated once and reused by
 * both rules that enforce it, so the two can never drift apart.
 */
const OUTPUT_ISOLATION_MESSAGE =
  'The projector bundle (src/output/) must not import from src/main/. ' +
  'It is a separate Vite entry whose size backs the 28 MB Projector Output ' +
  'line in the PRD §5.1 memory budget, and the bundle separation is a ' +
  'contract (PRD §6.3). Shared code belongs in src/shared/.'

/**
 * The rule that actually earns its keep is `no-restricted-imports` at the
 * bottom. Everything above it is the ordinary recommended stack.
 *
 * Type-aware linting (`recommendedTypeChecked`) is deliberately not enabled:
 * it needs a `projectService` pass over every file on every run, and
 * `npm run typecheck` (`vue-tsc`) already covers the type dimension. If a
 * later item wants a rule that only exists in the type-aware set, that is the
 * moment to pay for it.
 */
export default tseslint.config(
  {
    // Flat config applies `ignores` globally only in a block of its own.
    ignores: [
      'dist/',
      'node_modules/',
      'src-tauri/target/',
      // Regenerated by tauri-build on every compile.
      'src-tauri/gen/',
      // Generated from Rust (NFR-33); the generator owns their style.
      'src/shared/bindings/',
    ],
  },

  js.configs.recommended,
  tseslint.configs.recommended,
  vue.configs['flat/recommended'],

  {
    // Frontend sources: both entry bundles run in the WebView2 renderer.
    files: ['src/**/*.{ts,vue}'],
    languageOptions: {
      globals: globals.browser,
    },
  },

  {
    // `.vue` files are parsed by vue-eslint-parser, which needs to be told
    // which parser to hand `<script lang="ts">` blocks to.
    files: ['**/*.vue'],
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
      },
    },
  },

  {
    // Build tooling and the `postbuild`/`preinstall` hooks run under Node.
    files: ['scripts/**/*.js', '*.config.{js,ts}'],
    languageOptions: {
      globals: globals.node,
    },
  },

  {
    // The two bundle roots. `vue/multi-word-component-names` guards against a
    // component name colliding with a current or future HTML element, which can
    // only happen for a component used as a tag in someone else's template.
    // These two are mounted by `createApp(...)` and never written as tags, and
    // PRD §6.13 names `src/output/Renderer.vue` explicitly. The rule stays on
    // everywhere else.
    files: ['src/main/App.vue', 'src/output/Renderer.vue'],
    rules: {
      'vue/multi-word-component-names': 'off',
    },
  },

  {
    // PRD §6.3: `src/output/` is a separate bundle whose size is a budget line,
    // not an implementation detail. Reaching into `src/main/` compiles fine and
    // looks harmless in review — it just pulls views, stores and eventually the
    // Template Builder into the projector bundle, and the cost only shows up as
    // a memory number nobody is measuring during the change.
    //
    // Every spelling a developer would reach for is covered: the relative
    // forms (`../main/App.vue`, `./../main/...`, `../../main/...`) and the
    // aliased forms, in case a path alias is introduced later. The reverse
    // direction is not restricted — the Control Panel may legitimately share
    // code with the renderer — and `src/shared/**` stays open to both.
    files: ['src/output/**/*.{ts,vue}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/main', '**/main/**', '@/main', '@/main/**'],
              message: OUTPUT_ISOLATION_MESSAGE,
            },
          ],
        },
      ],

      // `no-restricted-imports` only inspects static import and re-export
      // declarations — verified against this ESLint version, a dynamic
      // `import('../main/App.vue')` passes it untouched. Lazy loading is
      // exactly how Control Panel code would realistically end up in the
      // projector bundle, so the dynamic form is closed here.
      'no-restricted-syntax': [
        'error',
        {
          selector: String.raw`ImportExpression > Literal[value=/(^|\/)main\//]`,
          message: OUTPUT_ISOLATION_MESSAGE,
        },
      ],
    },
  },

  // Last: switches off the stylistic rules Prettier owns, so the two tools
  // never disagree about the same line.
  prettier,
)
