// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The canvas shapes a template may be authored for.
 */
export type AspectRatio = "16:9" | "16:10" | "4:3";
