// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GradientStop } from "./GradientStop";
import type { ImageFit } from "./ImageFit";

/**
 * What a background layer is painted with. The `kind` field selects the
 * variant.
 */
export type BackgroundFill = { "kind": "solid", 
/**
 * `#RGB` or `#RRGGBB`.
 */
color: string, } | { "kind": "gradient", 
/**
 * Direction in degrees, as CSS measures it: 0 points up, 180 points
 * down.
 */
angle_deg: number, 
/**
 * Between 2 and 16 colour stops, in the order given.
 */
stops: Array<GradientStop>, } | { "kind": "image", 
/**
 * Canonical UUID of the asset in `media_assets`. That it exists, and
 * that it resolves inside a permitted media root, is checked by the
 * caller and not by the template validator.
 */
media_id: string, 
/**
 * How the image is fitted to the canvas.
 */
fit: ImageFit, 
/**
 * 0 is fully transparent, 1 fully opaque.
 */
opacity: number, 
/**
 * Blur applied to the image, as a fraction of canvas height. 0 is
 * sharp.
 */
blur_px_ratio: number, };
