// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AspectRatio } from "./AspectRatio";

/**
 * The canvas a template is authored against.
 *
 * Only `aspect_ratio` affects rendering. The reference size is authoring
 * information — geometry is normalised (FR-406), so the same document paints
 * proportionally on any output.
 */
export type Canvas = { 
/**
 * Shape of the canvas box.
 */
aspect_ratio: AspectRatio, 
/**
 * Width the template was authored against, in pixels. A reference only: it
 * is not checked against `aspect_ratio` and it constrains no output.
 */
reference_width: number, 
/**
 * Height the template was authored against, in pixels. Same status as
 * `reference_width`.
 */
reference_height: number, };
