// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One stop of a gradient.
 */
export type GradientStop = { 
/**
 * Position along the gradient: 0 at the start, 1 at the end.
 */
offset: number, 
/**
 * `#RGB` or `#RRGGBB`.
 */
color: string, };
