// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a background image is fitted to a canvas of a different shape.
 */
export type ImageFit = "cover" | "contain" | "stretch" | "tile";
