// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundFill } from "./BackgroundFill";
import type { Rect } from "./Rect";
import type { ShapeFill } from "./ShapeFill";
import type { ShapeGeometry } from "./ShapeGeometry";
import type { Stroke } from "./Stroke";
import type { TextEffects } from "./TextEffects";
import type { TextRole } from "./TextRole";
import type { Typography } from "./Typography";

/**
 * One painted layer.
 *
 * The `type` field selects the variant. A layer whose `type` is anything other
 * than `background`, `shape` or `text` is rejected when the document is
 * loaded: there is no pass-through case, and no way to carry a payload the
 * renderer does not understand.
 */
export type Layer = { "type": "background", 
/**
 * Canonical UUID, unique within this document.
 */
id: string, 
/**
 * `false` hides the layer without removing it.
 */
visible: boolean, 
/**
 * What the background is painted with.
 */
fill: BackgroundFill, } | { "type": "shape", 
/**
 * Canonical UUID, unique within this document.
 */
id: string, 
/**
 * `false` hides the layer without removing it.
 */
visible: boolean, 
/**
 * Where and what the shape is.
 */
geometry: ShapeGeometry, 
/**
 * Interior colour.
 */
fill: ShapeFill, 
/**
 * Outline. A `width` of 0 draws none.
 */
stroke: Stroke, 
/**
 * Blur applied to the layer, as a fraction of canvas height. 0 is
 * sharp.
 */
blur_px_ratio: number, } | { "type": "text", 
/**
 * Canonical UUID, unique within this document.
 */
id: string, 
/**
 * `false` hides the layer without removing it.
 */
visible: boolean, 
/**
 * Which piece of the item's content lands in this slot.
 */
role: TextRole, 
/**
 * The slot, in normalised units.
 */
box: Rect, 
/**
 * How the text in the slot is set.
 */
typography: Typography, 
/**
 * Shadow and outline treatment, for legibility over a photograph.
 */
effects: TextEffects, };
