// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One numbered schema change.
 */
export type Migration = { 
/**
 * Version this migration brings the database to. Recorded in
 * `schema_migrations.version` and in `PRAGMA user_version`.
 */
version: number, 
/**
 * Human-readable name, used in nothing but error messages and the file
 * name.
 */
name: string, 
/**
 * The statements, run as one batch inside one transaction.
 */
sql: string, };
