// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A display reported by the operating system.
 *
 * All sizes and positions are physical pixels in the virtual-screen
 * coordinate space, exactly as the OS reports them: not logical pixels, and
 * not divided by `scaleFactor`.
 */
export type Monitor = { 
/**
 * Opaque, machine-local identity. Use it to refer to a display; do not
 * parse it and do not show it to a user — `name` is the field for that.
 */
id: string, 
/**
 * What the OS calls this display — on Windows the device name, such as
 * `\\.\DISPLAY1`.
 */
name: string, 
/**
 * Width in physical pixels.
 */
width: number, 
/**
 * Height in physical pixels.
 */
height: number, 
/**
 * X of the top-left corner in the virtual-screen space. Negative for a
 * display arranged to the left of the primary.
 */
x: number, 
/**
 * Y of the top-left corner in the virtual-screen space.
 */
y: number, 
/**
 * Logical-to-physical pixel ratio: 1.0 at 96 DPI, 1.5 at 150% scaling.
 */
scaleFactor: number, 
/**
 * Whether the OS considers this the primary display.
 */
isPrimary: boolean, };
