// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An outline around the glyphs. As with the shadow, its settings survive being
 * disabled.
 */
export type OutlineEffect = { 
/**
 * Whether the outline is drawn.
 */
enabled: boolean, 
/**
 * `#RGB` or `#RRGGBB`.
 */
color: string, 
/**
 * Outline width as a fraction of canvas height.
 */
width: number, };
