// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A normalised box: the text slot of a layer, or the safe area of a document.
 *
 * `x` and `y` are the top-left corner. All four numbers are fractions of the
 * canvas, never pixels (FR-406). Positions may run slightly outside `0..1` for
 * a bleed; extents may not be negative.
 */
export type Rect = { 
/**
 * Left edge, normalised.
 */
x: number, 
/**
 * Top edge, normalised.
 */
y: number, 
/**
 * Width, normalised.
 */
w: number, 
/**
 * Height, normalised.
 */
h: number, };
