// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resolved passage: one book, and a range running from one point to
 * another.
 *
 * The range is closed and both ends are always filled in, so a consumer never
 * has to reconstruct a missing end. `Yoh 3:16` has both ends equal;
 * `Mzm 23` — a whole chapter — has `startChapter === endChapter` and both
 * verses `null`; `Kej 1:1-2:3` crosses chapters.
 *
 * `startVerse` and `endVerse` are `null` together or set together. `null`
 * means "every verse of that chapter", so a range that begins mid-chapter and
 * ends on a whole chapter has no representation here — and no spelling of it
 * parses.
 *
 * Nothing here has been checked against an actual Bible. The book exists in
 * the lookup table the reference was resolved against; the numbers are only
 * known to be at least 1 and to run forwards. Whether chapter 151 of Psalms
 * exists is a question about verse data, not about a reference.
 */
export type ScriptureRef = { 
/**
 * Canonical book id, in the 1–66 order `bible_books` uses.
 */
bookId: number, 
/**
 * First chapter of the passage. Chapters are numbered from 1.
 */
startChapter: number, 
/**
 * First verse, numbered from 1, or `null` for "from the start of the
 * chapter".
 */
startVerse: number | null, 
/**
 * Last chapter of the passage. Never earlier than `startChapter`.
 */
endChapter: number, 
/**
 * Last verse, numbered from 1, or `null` for "to the end of the chapter".
 * `null` exactly when `startVerse` is `null`.
 */
endVerse: number | null, };
