// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A drop shadow. Every field is still carried when `enabled` is `false`, so
 * turning it back on in the Builder restores the settings.
 */
export type ShadowEffect = { 
/**
 * Whether the shadow is drawn.
 */
enabled: boolean, 
/**
 * `#RGB` or `#RRGGBB`.
 */
color: string, 
/**
 * 0 is fully transparent, 1 fully opaque.
 */
opacity: number, 
/**
 * Blur radius as a fraction of canvas height.
 */
blur: number, 
/**
 * Horizontal offset as a fraction of canvas height. May be negative.
 */
offset_x: number, 
/**
 * Vertical offset as a fraction of canvas height. May be negative.
 */
offset_y: number, };
