// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The interior colour of a shape.
 */
export type ShapeFill = { 
/**
 * `#RGB` or `#RRGGBB`.
 */
color: string, 
/**
 * 0 is fully transparent, 1 fully opaque. A scrim is typically 0.5–0.7.
 */
opacity: number, };
