// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where and what a shape layer is. The `kind` field selects the variant, and
 * every variant carries the same normalised box.
 */
export type ShapeGeometry = { "kind": "rect", 
/**
 * Left edge, normalised.
 */
x: number, 
/**
 * Top edge, normalised.
 */
y: number, 
/**
 * Width, normalised.
 */
w: number, 
/**
 * Height, normalised.
 */
h: number, } | { "kind": "rounded_rect", 
/**
 * Left edge, normalised.
 */
x: number, 
/**
 * Top edge, normalised.
 */
y: number, 
/**
 * Width, normalised.
 */
w: number, 
/**
 * Height, normalised.
 */
h: number, 
/**
 * Corner radius as a fraction of canvas height. Only this kind of
 * shape has one.
 */
corner_radius: number, } | { "kind": "ellipse", 
/**
 * Left edge, normalised.
 */
x: number, 
/**
 * Top edge, normalised.
 */
y: number, 
/**
 * Width, normalised.
 */
w: number, 
/**
 * Height, normalised.
 */
h: number, } | { "kind": "path", 
/**
 * Left edge, normalised.
 */
x: number, 
/**
 * Top edge, normalised.
 */
y: number, 
/**
 * Width, normalised.
 */
w: number, 
/**
 * Height, normalised.
 */
h: number, 
/**
 * SVG path data. Only path commands, numbers and separators may appear
 * in it; that the commands form a legal path is checked separately
 * before it is drawn (FR-403).
 */
d: string, 
/**
 * The `viewBox` the path data is expressed in: four numbers, usually
 * `0 0 1 1`.
 */
viewbox: string, };
