// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of fitting one text slot's content: the slides it became, and
 * the type size all of them are set at.
 *
 * This is **not** Appendix D's `Slide`. A `Slide` is one projected screen and
 * carries an id, an item and a template; this is the piece that answers "what
 * text goes on each of them", and `slides[i]` is what becomes that slide's
 * `content.primary` (or `content.reference`, for the slot it was computed
 * against).
 *
 * Computed once, in Rust, and carried in the slide payload. Neither the
 * Control Panel preview nor the Projector Output may recompute it — that they
 * share one answer is what makes the preview trustworthy (risk R5).
 */
export type SlideSplit = { 
/**
 * One entry per slide, in order. Lines within a slide are joined with
 * `\n` and must be rendered as authored — the renderer may not re-wrap
 * them, or the count this split was built on no longer holds.
 *
 * **This text is untrusted and must enter the DOM as a text node, never
 * as HTML.** It is whatever a `.aero` file written by another program, a
 * PPTX or PDF import, or an operator's paste contained (FR-703, FR-501),
 * and building markup out of it — `innerHTML`, `v-html`, a template
 * string — runs that file's script in the origin the Control Panel shares
 * (ADR-0042). The safe answer is also the correct one: with
 * `white-space: pre` the `\n` between two lines *is* a line break, so
 * `el.textContent = slides[i]` renders exactly as intended and no `<br>`
 * is needed anywhere.
 *
 * Never empty: content that produces nothing to show still produces one
 * empty slide, so an item is never a dead end to navigate into (FR-306,
 * FR-313).
 */
slides: Array<string>, 
/**
 * The type size to render every slide in this list at, as a fraction of
 * canvas height — the template's `size`, or a smaller value down to
 * `min_size` if shrinking was what made the content fit.
 *
 * It is one value for the whole list on purpose: the type does not change
 * size between two slides of the same song.
 *
 * **Range.** Positive, finite, and no larger than the template's own
 * `size`, for any document `validate_template` accepted. It is not
 * clamped: a document that skipped validation can declare `size: 0` or
 * `size: -0.05`, and this field reports that number back rather than
 * inventing a plausible one in its place. What holds instead is the
 * pairing — whenever `fontSize` is not positive and finite, `overflows`
 * is `true` for any content with a line that shows something, because no
 * line box fits at such a size. (Content that is empty or nothing but
 * blank lines is the one exception, and not a leak: it renders as a single
 * empty slide, so there is nothing to spill and nothing to warn about.)
 * Read a non-positive `fontSize` as a broken template to report, not as a
 * size to paint at.
 */
fontSize: number, 
/**
 * `true` when the content has a line that shows something and the slot is
 * too short for even a single line at `min_size`, so at least one line
 * will spill out of its box however the content is divided. Splitting
 * cannot fix it — only a taller slot, a smaller `min_size`, or less text
 * can. Surface it (FR-407); the point of US-16 is that nobody discovers
 * this from the congregation's side of the screen.
 *
 * Content that is empty or nothing but blank lines never sets it, however
 * short the slot: it renders as one empty slide, and nothing spills out of
 * anything.
 *
 * This is not "the content was split". That is `slides.length > 1`, and it
 * is the ordinary, healthy outcome.
 *
 * **It is a vertical, line-box claim and only that.** It does not report a
 * line too wide for its slot — no font metrics reach the crate that
 * computed this — and it does not report glyph ink painted outside a line
 * box that itself fits, which is what a `line_height` below about 1.2
 * produces: CSS half-leading goes negative there, and the first line's
 * ascenders and the last line's descenders land outside the slot with
 * `overflows` still `false`. Both are the renderer's to detect and to
 * surface (FR-407); a `false` here is not a promise that the slide looks
 * right.
 */
overflows: boolean, };
