// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outline of a shape.
 */
export type Stroke = { 
/**
 * `#RGB` or `#RRGGBB`.
 */
color: string, 
/**
 * Line width as a fraction of canvas height. 0 draws no outline.
 */
width: number, 
/**
 * 0 is fully transparent, 1 fully opaque.
 */
opacity: number, };
