// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Canvas } from "./Canvas";
import type { Layer } from "./Layer";
import type { Rect } from "./Rect";
import type { TemplateMetadata } from "./TemplateMetadata";

/**
 * A complete template: a canvas, an ordered stack of layers, a safe area and
 * its metadata.
 *
 * This is the document stored in `templates.document` and exported as
 * `.aerotpl` (FR-409). The field names are exactly Appendix B's, so a value of
 * this type and the JSON on disk are one thing spelled twice.
 *
 * **A value of this type has not necessarily been validated**: deserialising
 * one checks its *shape* and never its values, so ranges, colour spelling and
 * id spelling hold only for a document that came back from `parse_template` or
 * `validate_template`.
 */
export type TemplateDocument = { 
/**
 * Version of the template schema this document is written in. Only `1`
 * exists; anything else is refused on load with a message naming the
 * version, rather than as a parse failure.
 */
schema_version: number, 
/**
 * Stable identity of the template, as a canonical UUID.
 */
id: string, 
/**
 * What the operator sees in the template picker. Never blank.
 */
name: string, 
/**
 * The abstract box every coordinate in this document is relative to.
 */
canvas: Canvas, 
/**
 * Painted in array order: index 0 is the back layer and the last entry is
 * on top. At most 32 entries.
 */
layers: Array<Layer>, 
/**
 * The region content is expected to stay inside, drawn as a guide in the
 * Builder (FR-407). It constrains nothing at render time.
 */
safe_area: Rect, 
/**
 * Authoring provenance. Not used for rendering.
 */
metadata: TemplateMetadata, };
