// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authoring provenance. None of it affects rendering.
 */
export type TemplateMetadata = { 
/**
 * When the template was first saved, as an ISO-8601 timestamp.
 *
 * Checked for shape and length only — this crate does not own a calendar,
 * so `2026-13-45T99:99:99Z` is accepted as a string and is not a date.
 */
created_at: string, 
/**
 * When the template was last saved. Same status as `created_at`.
 */
updated_at: string, 
/**
 * Who authored it. May be empty.
 */
author: string, };
