// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The semantic slot a text layer binds to (PRD §6.7).
 *
 * A template declares the role; the session item supplies the text. A role the
 * current content type does not provide simply renders nothing, which is what
 * makes one template reusable across songs, scripture and media.
 */
export type TextRole = "primary" | "secondary" | "reference" | "attribution";
