// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Case transformation applied to a text slot at render time.
 */
export type TextTransform = "none" | "uppercase" | "capitalize";
