// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutlineEffect } from "./OutlineEffect";
import type { ShadowEffect } from "./ShadowEffect";

/**
 * Legibility treatment for a text slot over a photographic background.
 */
export type TextEffects = { 
/**
 * Drop shadow behind the text.
 */
shadow: ShadowEffect, 
/**
 * Outline drawn around the glyphs.
 */
outline: OutlineEffect, };
