// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HorizontalAlign } from "./HorizontalAlign";
import type { TextTransform } from "./TextTransform";
import type { VerticalAlign } from "./VerticalAlign";

/**
 * How the text in a slot is set.
 */
export type Typography = { 
/**
 * Preferred font family. Whether it is installed on the machine showing
 * the slide is not checked here.
 */
font_family: string, 
/**
 * Families to fall back to, in order, ending at a generic family such as
 * `sans-serif`. At most 8.
 */
font_fallback: Array<string>, 
/**
 * CSS font weight, 1–1000. 400 is regular, 700 is bold.
 */
weight: number, 
/**
 * Type size as a fraction of canvas height — this is what makes a template
 * resolution-independent (FR-406).
 */
size: number, 
/**
 * The floor the renderer may shrink to before splitting the content across
 * slides instead (FR-310). Never larger than `size`.
 */
min_size: number, 
/**
 * Line box height as a multiple of the type size.
 */
line_height: number, 
/**
 * Extra space between characters, as a fraction of canvas height. May be
 * negative, to tighten.
 */
letter_spacing: number, 
/**
 * Case transformation applied at render time.
 */
transform: TextTransform, 
/**
 * `#RGB` or `#RRGGBB`.
 */
color: string, 
/**
 * Horizontal alignment inside the slot.
 */
align_h: HorizontalAlign, 
/**
 * Vertical alignment inside the slot.
 */
align_v: VerticalAlign, 
/**
 * Lines that fit in the slot before the content is split onto another
 * slide (FR-310). 1–64.
 */
max_lines: number, };
