// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Vertical alignment of text inside its slot.
 */
export type VerticalAlign = "top" | "middle" | "bottom";
