// @ts-check

/**
 * Pure-function coverage for `bindings-guard.js` (NFR-33), which landed with
 * none — the implementer named that gap themselves as an ADR-0020 case left
 * open: the guard's verdict was demonstrated once by hand, red then green, and
 * a demonstration is not a gate. `check-bindings.js` itself (spawning cargo,
 * reading directories, printing) stays out of scope here, the same division
 * `dist-html-guard.test.js` draws against `check-dist-html.js`; the whole
 * reason `bindings-guard.js` holds no I/O is so these decisions can be driven
 * with literal strings and no Rust toolchain.
 *
 * The clause that gets the most cases is `generatedNothing`. Every other check
 * asks whether two sides disagree, and two empty sides agree perfectly — so
 * without that clause, deleting the last `#[ts(export)]`, or a ts-rs release
 * that renames its generated tests out from under the `export_bindings`
 * filter, would leave this guard printing "in sync" about a contract nobody
 * generated. `cargo test <filter>` exits 0 when the filter matches nothing, so
 * that is not hypothetical: it is the most likely way the whole mechanism gets
 * switched off silently.
 */

import { describe, expect, it } from 'vitest'

import {
  compareBindings,
  describeFirstDifference,
  summariseComparison,
} from './bindings-guard.js'

/** A binding of the shape ts-rs actually emits, so the fixtures read true. */
const MIGRATION_TS = `// This file was generated by [ts-rs]. Do not edit this file manually.

export type Migration = { version: number, name: string, };
`

/**
 * @param {Record<string, string>} entries
 * @returns {Map<string, string>}
 */
function bindings(entries) {
  return new Map(Object.entries(entries))
}

describe('summariseComparison — an empty run is a failure, not a clean one', () => {
  it('FAILS when the generator produced nothing, even though both sides agree perfectly', () => {
    // The load-bearing case: `cargo test export_bindings` exits 0 when the
    // filter matches nothing, so the guard reaches here with two empty maps
    // and no disagreement whatsoever. Reporting "in sync" would be true and
    // useless — nothing was verified.
    const comparison = compareBindings(new Map(), new Map())
    expect(comparison).toEqual({
      missing: [],
      unexpected: [],
      differing: [],
      matching: [],
    })

    const summary = summariseComparison(comparison)
    expect(summary.exitCode).toBe(1)
    expect(summary.generatedNothing).toBe(true)
    expect(summary.inspected).toBe(0)
  })

  it('FAILS when the generator produced nothing but files are still committed', () => {
    // The shape of "the last `#[ts(export)]` was deleted, the bindings were
    // not". `unexpected` is non-empty, so this would fail anyway — asserted so
    // that `generatedNothing` is still reported as the *reason*, which is what
    // sends the reader to the cargo filter instead of to the committed files.
    const summary = summariseComparison(
      compareBindings(new Map(), bindings({ 'Migration.ts': MIGRATION_TS })),
    )
    expect(summary.exitCode).toBe(1)
    expect(summary.generatedNothing).toBe(true)
    expect(summary.inspected).toBe(0)
  })

  it('does NOT report generatedNothing when exactly one file was generated', () => {
    // The boundary: one generated file is a real run. If `generatedNothing`
    // were ever computed from the committed side, or from `matching` alone,
    // this is where that would show.
    const summary = summariseComparison(
      compareBindings(
        bindings({ 'Migration.ts': MIGRATION_TS }),
        bindings({ 'Migration.ts': MIGRATION_TS }),
      ),
    )
    expect(summary.generatedNothing).toBe(false)
    expect(summary.inspected).toBe(1)
    expect(summary.exitCode).toBe(0)
  })

  it('counts every generated file as inspected, whether it matched, differed or was missing', () => {
    // `inspected` is the "this really ran" number the empty-run clause reads,
    // so it must not be `matching.length` in disguise: a run where nothing
    // matched still inspected files.
    const summary = summariseComparison(
      compareBindings(
        bindings({
          'Migration.ts': MIGRATION_TS,
          'Slide.ts': 'export type Slide = { id: string, };\n',
          'New.ts': 'export type New = { a: number, };\n',
        }),
        bindings({
          'Migration.ts': MIGRATION_TS,
          'Slide.ts': 'export type Slide = { id: number, };\n',
        }),
      ),
    )
    expect(summary.inspected).toBe(3) // 1 matching + 1 differing + 1 missing
    expect(summary.generatedNothing).toBe(false)
    expect(summary.exitCode).toBe(1)
  })

  it('does not count a committed-only file as inspected', () => {
    const summary = summariseComparison(
      compareBindings(
        bindings({ 'Migration.ts': MIGRATION_TS }),
        bindings({
          'Migration.ts': MIGRATION_TS,
          'Leftover.ts': 'export type X = {};\n',
        }),
      ),
    )
    expect(summary.inspected).toBe(1)
    expect(summary.exitCode).toBe(1)
  })
})

describe('summariseComparison — exit code per drift shape', () => {
  it('is 0 only when every generated file is committed and identical', () => {
    const summary = summariseComparison(
      compareBindings(
        bindings({
          'Migration.ts': MIGRATION_TS,
          'session/Slide.ts': 'export type S={};\n',
        }),
        bindings({
          'Migration.ts': MIGRATION_TS,
          'session/Slide.ts': 'export type S={};\n',
        }),
      ),
    )
    expect(summary).toEqual({ exitCode: 0, inspected: 2, generatedNothing: false })
  })

  it('fails on a differing file', () => {
    expect(
      summariseComparison({
        missing: [],
        unexpected: [],
        differing: ['Migration.ts'],
        matching: [],
      }).exitCode,
    ).toBe(1)
  })

  it('fails on a missing file', () => {
    expect(
      summariseComparison({
        missing: ['Migration.ts'],
        unexpected: [],
        differing: [],
        matching: [],
      }).exitCode,
    ).toBe(1)
  })

  it('fails on an unexpected file even when every generated file matched', () => {
    // The hand-written-file case (PRD §6.13, "do not edit") and the
    // removed-Rust-type leftover. `matching` is non-empty here, so a guard
    // that only asked "did everything I generated line up?" would pass.
    expect(
      summariseComparison({
        missing: [],
        unexpected: ['Leftover.ts'],
        differing: [],
        matching: ['Migration.ts'],
      }).exitCode,
    ).toBe(1)
  })
})

describe('compareBindings', () => {
  it('sorts every bucket, so a diagnostic reads the same on two machines', () => {
    // Directory listings come back in different orders on different
    // filesystems; the guard's output must not.
    const comparison = compareBindings(
      bindings({ 'z.ts': 'a\n', 'a.ts': 'a\n', 'm.ts': 'x\n', 'b.ts': 'new\n' }),
      bindings({ 'm.ts': 'y\n', 'a.ts': 'a\n', 'z.ts': 'a\n', 'w.ts': 'old\n' }),
    )
    expect(comparison.matching).toEqual(['a.ts', 'z.ts'])
    expect(comparison.differing).toEqual(['m.ts'])
    expect(comparison.missing).toEqual(['b.ts'])
    expect(comparison.unexpected).toEqual(['w.ts'])
  })

  it('compares byte-for-byte: a difference in whitespace alone is still drift', () => {
    // "Is the committed file the file the generator would produce right now",
    // not "are these two contracts compatible". A guard that normalised
    // whitespace would start having opinions about which differences matter.
    const comparison = compareBindings(
      bindings({ 'Migration.ts': 'export type M = { a: number, };\n' }),
      bindings({ 'Migration.ts': 'export type M = { a: number,  };\n' }),
    )
    expect(comparison.differing).toEqual(['Migration.ts'])
    expect(comparison.matching).toEqual([])
  })

  it('treats a trailing-newline difference as drift', () => {
    const comparison = compareBindings(
      bindings({ 'Migration.ts': `${MIGRATION_TS}` }),
      bindings({ 'Migration.ts': MIGRATION_TS.trimEnd() }),
    )
    expect(comparison.differing).toEqual(['Migration.ts'])
  })

  it('keys by path relative to the bindings directory, so a subdirectory is not a bare name', () => {
    // `#[ts(export_to = "session/Slide.ts")]` must compare against
    // `session/Slide.ts`, never against `Slide.ts` — otherwise a type moved
    // between subdirectories reads as "unchanged".
    const comparison = compareBindings(
      bindings({ 'session/Slide.ts': 'export type Slide = {};\n' }),
      bindings({ 'Slide.ts': 'export type Slide = {};\n' }),
    )
    expect(comparison.missing).toEqual(['session/Slide.ts'])
    expect(comparison.unexpected).toEqual(['Slide.ts'])
    expect(comparison.matching).toEqual([])
    expect(summariseComparison(comparison).exitCode).toBe(1)
  })

  it('reports a file present on neither side as nothing at all', () => {
    const comparison = compareBindings(new Map(), new Map())
    expect(comparison.missing).toEqual([])
    expect(comparison.unexpected).toEqual([])
  })

  it('handles both drift directions in one comparison without confusing them', () => {
    const comparison = compareBindings(
      bindings({ 'Kept.ts': 'a\n', 'Added.ts': 'b\n', 'Edited.ts': 'new\n' }),
      bindings({ 'Kept.ts': 'a\n', 'Removed.ts': 'c\n', 'Edited.ts': 'old\n' }),
    )
    expect(comparison).toEqual({
      matching: ['Kept.ts'],
      missing: ['Added.ts'],
      unexpected: ['Removed.ts'],
      differing: ['Edited.ts'],
    })
  })
})

describe('describeFirstDifference — the line number in the diagnostic', () => {
  it('returns null for identical content', () => {
    expect(describeFirstDifference(MIGRATION_TS, MIGRATION_TS)).toBeNull()
  })

  it('reports the FIRST differing line, 1-based, not the last or a count', () => {
    const generated = 'line one\nline two\nline three\n'
    const committed = 'line one\nline TWO\nline THREE\n'
    expect(describeFirstDifference(generated, committed)).toEqual({
      line: 2,
      generated: 'line two',
      committed: 'line TWO',
    })
  })

  it('reports line 1 when the very first line differs', () => {
    expect(describeFirstDifference('a\nsame\n', 'b\nsame\n')).toEqual({
      line: 1,
      generated: 'a',
      committed: 'b',
    })
  })

  it('reports a field added at the end of the generated file as the first line only it has', () => {
    // One file is a prefix of the other — the shape of a field or a whole type
    // appended to a Rust struct.
    const generated = 'export type M = {\n  a: number,\n  b: string,\n}\n'
    const committed = 'export type M = {\n  a: number,\n'
    expect(describeFirstDifference(generated, committed)).toEqual({
      line: 3,
      generated: '  b: string,',
      committed: '',
    })
  })

  it('uses null for the side that has no such line at all', () => {
    const generated = 'a\nb\nc'
    const committed = 'a\nb'
    expect(describeFirstDifference(generated, committed)).toEqual({
      line: 3,
      generated: 'c',
      committed: null,
    })
    expect(describeFirstDifference(committed, generated)).toEqual({
      line: 3,
      generated: null,
      committed: 'c',
    })
  })

  it('strips a trailing CR, so two lines differing only in line ending are not reported as differing', () => {
    // Line 1 differs in raw bytes (a `\r`) and line 2 differs in content. The
    // reader must be pointed at line 2 — the real contract change — and not at
    // line 1, where the two lines would print identically and read as a
    // nonsense diff.
    const generated = 'export type M = {};\nexport type N = { a: number, };\n'
    const committed = 'export type M = {};\r\nexport type N = { a: string, };\n'
    expect(describeFirstDifference(generated, committed)).toEqual({
      line: 2,
      generated: 'export type N = { a: number, };',
      committed: 'export type N = { a: string, };',
    })
  })

  it('pure CRLF-vs-LF drift is real drift, and returns null on both sides one line past the end of the file', () => {
    // `compareBindings` compares raw bytes, so this IS drift and the run
    // fails — correct, and asserted first. The return value is the part worth
    // pinning: after the CR strip the two line arrays are byte-identical, so
    // no shared index differs and the fallback branch fires — `line` is
    // `shared + 1`, one past the last line of both files, with `null` on both
    // sides. There is no line to name here, and this function does not invent
    // one.
    //
    // This return value used to be reported as an overpromise, because
    // `check-bindings.js` fed it straight into `first difference at line 3:
    // generated now: (no such line) / committed: (no such line)` — a
    // diagnostic naming neither the line ending nor any real line, while this
    // function's doc promised "a message that says so instead of a diff where
    // both lines look the same". The gap was in the *printing*, and that is
    // where it was closed: `check-bindings.js` now branches on both sides
    // being `null` and prints the line-ending message, keeping the promise
    // this shape makes recognisable. Pinned here so that contract stays
    // legible from the value side; the printed half is asserted in
    // `tests/unit/check-bindings.diagnostics.test.js`. Narrow in practice
    // (`.gitattributes` has to fail first for this to be reachable) — but the
    // two halves only mean anything together, so neither is left untested.
    const generated = 'export type M = {};\n'
    const committed = 'export type M = {};\r\n'
    const comparison = compareBindings(
      bindings({ 'M.ts': generated }),
      bindings({ 'M.ts': committed }),
    )
    expect(comparison.differing).toEqual(['M.ts'])
    expect(summariseComparison(comparison).exitCode).toBe(1)
    expect(describeFirstDifference(generated, committed)).toEqual({
      line: 3,
      generated: null,
      committed: null,
    })
  })

  it('is a diagnostic only: it never decides, and says nothing about the verdict', () => {
    // Guards against the shape where a future edit makes the verdict depend on
    // this function — e.g. "no reportable line difference, so not really
    // drift". `compareBindings` has already decided by the time this runs.
    const generated = 'same\n'
    const committed = 'same\n'
    expect(describeFirstDifference(generated, committed)).toBeNull()
    expect(
      summariseComparison(
        compareBindings(bindings({ 'M.ts': generated }), bindings({ 'M.ts': committed })),
      ).exitCode,
    ).toBe(0)
  })
})
